name: "Dependabot Auto Approve and Merge"
on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  call-automerge:
    uses: flowlogix/base-pom/.github/workflows/dependabot-automerge.yml@automerge-non-dependabot
    secrets:
      github-token: ${{ secrets.GH_AUTOMERGE_TOKEN }}
